# Generated by Django 4.0.1 on 2022-02-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_cast_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrival',
            name='desc',
        ),
        migrations.AlterField(
            model_name='newarrival',
            name='casting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.cast'),
        ),
        migrations.AlterField(
            model_name='newarrival',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.director'),
        ),
    ]
