# Generated by Django 4.0.1 on 2022-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_newarrival_desc_alter_newarrival_casting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrival',
            name='casting',
        ),
        migrations.AddField(
            model_name='newarrival',
            name='casting',
            field=models.ManyToManyField(to='blogapp.Cast'),
        ),
    ]
