# Generated by Django 4.0.1 on 2022-02-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_remove_newarrival_casting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newarrival',
            options={'ordering': ['title']},
        ),
    ]
