# Generated by Django 4.0.1 on 2022-02-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_newarrival_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newarrival',
            options={'ordering': ['-title']},
        ),
    ]
