# Generated by Django 4.0.1 on 2022-02-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_newarrival_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarrival',
            name='casting',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.cast'),
        ),
    ]
